[package]
name = "druid-example-1"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
thiserror = "1.0.63"
druid = "0.8.3"
env_logger = "0.11"
log = "0.4"
dotenvy = "0.15"

[[example]]
name = "color_picker"

[[example]]
name = "color_picker_tutor"
